PhotoContests.App/Controllers/ContestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using PhotoContests.App.Models.BindingModels;
using PhotoContests.App.Models.ViewModels;
using PhotoContests.Data.UnitOfWork;
using PhotoContests.Models;

namespace PhotoContests.App.Controllers
{
    public class ContestsController : BaseController
    {
        public ContestsController(IPhotoContestsData data)
            : base(data)
        {
        }

        public ContestsController(IPhotoContestsData data, User user)
            : base(data, user)
        {
        }

        // GET: Contests
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var contests = this.Data.Contests.All()
                .OrderByDescending(c => c.DateCreated)
                .Where(c => (c.DateEnded > DateTime.Now || c.DateEnded == null) && c.ContestOwner.Id == userId);

            var contestModels = Mapper.Map<IEnumerable<Contest>, IEnumerable<ContestViewModel>>(contests);
            return View(contestModels);
        }

        // GET: Closed Contests
        public ActionResult ClosedContests()
        {
            var userId = User.Identity.GetUserId();
            var contests = this.Data.Contests.All()
                .OrderByDescending(c => c.DateCreated)
                .Where(c => c.DateEnded < DateTime.Now && c.ContestOwner.Id == userId);

            var contestModels = Mapper.Map<IEnumerable<Contest>, IEnumerable<ContestViewModel>>(contests);
            return View(contestModels);
        }

        // GET: Past Contests
        public ActionResult PastContests()
        {
            var contests = this.Data.Contests.All()
                .OrderByDescending(c => c.DateCreated)
                .Where(c => c.DateEnded < DateTime.Now);

            var contestModels = Mapper.Map<IEnumerable<Contest>, IEnumerable<ContestViewModel>>(contests);
            return View(contestModels);
        }

        // GET: Contests/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("NotFound","Error");
            }
            var contest = this.Data.Contests.Find(id);
            if (contest == null)
            {
                return RedirectToAction("NotFound", "Error");
            }

            if (contest.DateEnded < DateTime.Now)
            {
                this.FinalizeConfirmed(contest.Id);
            }

            var contestViewModel = Mapper.Map<Contest, ContestDetailViewModel>(contest);
            //var contestViewModel = new ContestDetailViewModel()
            //{
            //    Id = contest.Id,
            //    Title = contest.Title,
            //    DateCreated = contest.DateCreated,
            //    DateEnded = contest.DateEnded,
            //    Description = contest.Description,
            //    Owner = contest.ContestOwner.UserName,                
            //};

            //foreach (var contestPicture in contest.ContestPictures)
            //{
                
            //}

            //IEnumerable<WinnerPrizeViewModel> winners = null;

            //foreach (var contestWinner in contest.Prizes)
            //{
            //    string prize = contestWinner.Name;
            //    string winner = contestWinner.Winner.UserName;
            //    var currentWinner = new WinnerPrizeViewModel()
            //    {
            //        Name = prize,
            //        WinnerUsername = winner
            //    };
            //}

            //contestViewModel.Winners = winners;

            return View(contestViewModel);
        }

        // GET: Contests/Create
        public ActionResult TempCreate()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TempCreate(ContestBindingModel model)
        {
            this.Session["Title"] = model.Title;
            this.Session["Description"] = model.Description;
            this.Session["RewardStrategy"] = model.RewardStrategy;
            this.Session["VotingStrategy"] = model.VotingStrategy;
            this.Session["ParticipationStrategy"] = model.ParticipationStrategy;
            this.Session["DeadlineStrategy"] = model.DeadlineStrategy;
            return RedirectToAction("Create");
        }

        [HttpGet]
        public ActionResult Create()
        {
            this.LoadPrizes();
            this.LoadUsers();
            return View();
        }

        private void LoadUsers()
        {
            string userId = this.User.Identity.GetUserId();
            this.ViewBag.UserIds = this.Data.Users.All()
                .Where(u => u.Id != userId)
                .Select(u => new SelectListItem()
                {
                    Value = u.Id.ToString(),
                    Text = u.UserName
                });
        }

        private void LoadPrizes()
        {
            var userId = this.User.Identity.GetUserId();
            this.ViewBag.PrizeIds = this.Data.Prizes.All()
            .Where(u => u.OwnerId == userId && u.ContestId == null)
            .Select(u => new SelectListItem()
            {
                Value = u.Id.ToString(),
                Text = u.Name
            });
        }

        public ActionResult GetPartisipators()
        {
            this.LoadUsers();
            return this.PartialView("_AddPartisipatorPartialView");
        }

        public ActionResult GetPrizes()
        {
            this.LoadPrizes();
            return this.PartialView("_CreatePrizePartial");
        }

        public ActionResult GetVoters()
        {
            this.LoadUsers();
            return this.PartialView("_AddVoterPartialView");
        }

        // POST: Contests/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ContestFinalBindingModel model)
        {
            if (ModelState.IsValid)
            {
                var userId = User.Identity.GetUserId();
                var user = this.Data.Users.All().FirstOrDefault(u => u.Id == userId);

                string title = this.Session["Title"].ToString();
                string description = this.Session["Description"].ToString();
                string rewardStrategy = this.Session["RewardStrategy"].ToString();
                string votingStrategy = this.Session["VotingStrategy"].ToString();
                string participationStrategy = this.Session["ParticipationStrategy"].ToString();
                string deadlineStrategy = this.Session["DeadlineStrategy"].ToString();

                var contest = new Contest()
                {
                    Title = title,
                    Description = description,
                    DateCreated = DateTime.Now,
                    DateEnded = model.DateEnded,
                    RewardStrategy = rewardStrategy == RewardStrategy.SingleUser.ToString() ? RewardStrategy.SingleUser : RewardStrategy.TopNUsers,
                    VotingStrategy = votingStrategy == VotingStrategy.Open.ToString() ? VotingStrategy.Open : VotingStrategy.Closed,
                    ParticipationStrategy = participationStrategy == ParticipationStrategy.Open.ToString() ? ParticipationStrategy.Open : ParticipationStrategy.Closed,
                    DeadlineStrategy = deadlineStrategy == DeadlineStrategy.ByTime.ToString() ? DeadlineStrategy.ByTime : DeadlineStrategy.ByNumberOfParticipants,
                    ContestOwnerId = userId,
                    Winners = model.WinnersCount != null ? model.WinnersCount : null,
                    MaxParticipants = model.NumberOfParticipation != null ? model.NumberOfParticipation : null
                };

                this.Data.Contests.Add(contest);

                if (contest.ParticipationStrategy == ParticipationStrategy.Closed)
                {
                    foreach (var partisipatorId in model.PartisipatorIds)
                    {
                        var partisipator = this.Data.Users.Find(partisipatorId);
                        contest.SelectedUsersForParticipation.Add(partisipator);
                        var notification = new Notification
                        {
                            Content = "You are invited to participate in " + contest.Title + " contest.",
                            UserId = userId
                        };
                        partisipator.Notifications.Add(notification);

                    }
                }

                if (contest.VotingStrategy == VotingStrategy.Closed)
                {
                    foreach (var voterId in model.VoterIds)
                    {
                        var voter = this.Data.Users.Find(voterId);
                        contest.InvitedUsersForVoting.Add(voter);
                        var notification = new Notification()
                        {
                            Content = "You are invited for voting in " + contest.Title + " contest.",
                            UserId = userId
                        };
                        voter.Notifications.Add(notification);

                    }
                }

                if (model.PrizeIds.Any())
                {
                    foreach (var prizeId in model.PrizeIds)
                    {
                        var prize = this.Data.Prizes.Find(prizeId);
                        prize.ContestId = contest.Id;
                    }
                }
                
                this.Data.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            this.LoadPrizes();
            this.LoadUsers();

            return View();
        }

        // GET: Contests/Edit/5
        public ActionResult Edit(int? id)
        {
            var userId = this.User.Identity.GetUserId();

            if (id == null)
            {

PhotoContests.App/Controllers/PrizesController.cs
using System.Web.Mvc;
using AutoMapper;
using Microsoft.AspNet.Identity;
using PhotoContests.App.Models.BindingModels;
using PhotoContests.Data.UnitOfWork;
using PhotoContests.Models;

namespace PhotoContests.App.Controllers
{
    public class PrizesController : BaseController
    {
        public PrizesController(IPhotoContestsData data)
            : base(data)
        {
        }

        public PrizesController(IPhotoContestsData data, User user)
            : base(data, user)
        {
        }

        [HttpGet]
        public ActionResult Create()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PrizeBindingModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                var prize = Mapper.Map<Prize>(model);
                var userId = this.User.Identity.GetUserId();
                prize.OwnerId = userId;

                this.Data.Prizes.Add(prize);
                this.Data.SaveChanges();

                ViewBag.Success = "Success";
            }
            else
            {
                ViewBag.Success = "Failed";
            }

            return this.View();
        }
    }
}

PhotoContests.App/Views/Shared/_AddPartisipatorPartialView.cshtml
@using System.Collections.Generic
<div class="form-group">
    @Html.Label("User", new { @class = "col-md-2 control-label" })
    @Html.DropDownList("PartisipatorIds", (IEnumerable<SelectListItem>)this.ViewBag.UserIds, new { name = "PartisipatorIds[]", @class = "form-control" })
</div>

PhotoContests.App/Views/Shared/_AddVoterPartialView.cshtml
@using System.Collections.Generic
<div class="form-group">
    @Html.Label("User", new { @class = "col-md-2 control-label" })
    @Html.DropDownList("VoterIds", (IEnumerable<SelectListItem>)this.ViewBag.UserIds, new { name = "VoterIds[]", @class = "form-control" })
</div>

PhotoContests.App/Views/Shared/_CreatePrizePartial.cshtml
@using System.Collections.Generic
<div class="form-group">
    @Html.Label("Prize", new { @class = "col-md-2 control-label" })
    @Html.DropDownList("PrizeIds", (IEnumerable<SelectListItem>)this.ViewBag.PrizeIds, new { name = "PrizeIds[]", @class = "form-control" })
</div>

PhotoContests.App/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity 
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Photo contests", "Index", "Home", new { area = "" }, new { @class = "photo-contest-logo" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                @{
                    if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Admin", "Index", "HomeAdmin", routeValues: new {area = "Admin"}, htmlAttributes: null)</li>
                    }
                    if (User.Identity.IsAuthenticated)
                    {
                        <li role="presentation" class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                My contests <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="/Contests/Index">Active contests</a></li>
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="/Contests/ClosedContests">Closed contests</a></li>
                                <li role="presentation"><a role="menuitem" tabindex="-1" href="/Contests/tempcreate">Create Contest</a></li>
                            </ul>
                        </li>
                        <li>
                            @Html.ActionLink("Create Prize", "Create", "Prizes", null, htmlAttributes: null)
                        </li>
                        <li>
                            @Html.ActionLink("Notifications", "Index", "Notifications", null, htmlAttributes: null)
                        </li>
                    }
                }
                <li>@Html.ActionLink("Past Contests", "PastContests", "Contests")</li>               
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year - Photo Contests</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@Scripts.Render("~/bundles/signalr")
@RenderSection("scripts", required: false)
</body>
</html>